site_name: Hydro Models Docs
theme:
    readthedocs
plugins:
  - search
  - mkdocstrings:
       handlers:
          python:
             paths: [hydromodel]
  - section-index
  - gen-files:
      scripts:
      - gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
watch:
    - hydromodel
nav:
- Code Reference: docs/


